---
version: "3"
services:

    mariadb:
        container_name: mariadb
        image: mariadb:10.11
        restart: always
        networks:
            - network
        environment:
            MARIADB_DATABASE: ${DB_NAME}
            MARIADB_USER: ${DB_USER}
            MARIADB_PASSWORD: ${DB_PASSWORD}
            MARIADB_ROOT_PASSWORD: ${DB_ROOT_PASSWORD}
        volumes:
            - mariadb:/var/lib/mysql
        healthcheck:
            test: ["CMD", "healthcheck.sh", "--su-mysql", "--connect", "--innodb_initialized"]
            interval: 10s
            timeout: 10s
            retries: 5
            start_period: 0s

    wordpress:
        container_name: wordpress
        build:
            context: ./wordpress
            dockerfile: Dockerfile
        restart: always
        networks:
            - network
        depends_on:
            mariadb:
                condition: service_healthy
        volumes:
            - wordpress:/var/www/html
        environment:
            WORDPRESS_DEBUG: 1
            WORDPRESS_DB_HOST: mariadb:3306
            WORDPRESS_DB_USER: ${DB_USER}
            WORDPRESS_DB_PASSWORD: ${DB_PASSWORD}
            WORDPRESS_DB_NAME: ${DB_NAME}
            WORDPRESS_AUTH_KEY: ${WORDPRESS_AUTH_KEY}
            WORDPRESS_SECURE_AUTH_KEY: ${WORDPRESS_SECURE_AUTH_KEY}
            WORDPRESS_LOGGED_IN_KEY: ${WORDPRESS_LOGGED_IN_KEY}
            WORDPRESS_NONCE_KEY: ${WORDPRESS_NONCE_KEY}
            WORDPRESS_AUTH_SALT: ${WORDPRESS_AUTH_SALT}
            WORDPRESS_SECURE_AUTH_SALT: ${WORDPRESS_SECURE_AUTH_SALT}
            WORDPRESS_LOGGED_IN_SALT: ${WORDPRESS_LOGGED_IN_SALT}
            WORDPRESS_NONCE_SALT: ${WORDPRESS_NONCE_SALT}
            WP_URL: https://${DOMAIN_NAME}
            WP_TITLE: ${WP_TITLE}
            WP_ADMIN: ${WP_ADMIN}
            WP_ADMIN_PASSWORD: ${WP_ADMIN_PASSWORD}
            WP_ADMIN_MAIL: ${WP_ADMIN_MAIL}
            WP_USER: ${WP_USER}
            WP_USER_PASSWORD: ${WP_USER_PASSWORD}
            WP_USER_MAIL: ${WP_USER_MAIL}
    
    phpmyadmin:
        container_name: phpmyadmin
        image: phpmyadmin:5.2
        restart: always
        networks:
            - network
        depends_on:
            mariadb:
                condition: service_healthy
        environment:
            PMA_HOST: mariadb
            PMA_PORT: 3306
            PMA_ABSOLUTE_URI: https://${DOMAIN_NAME}/phpmyadmin/

    nginx:
        container_name: nginx
        build:
            context: ./nginx
            dockerfile: Dockerfile
        restart: always
        ports:
            - "80:80"
            - "443:443"
        networks:
            - network
        depends_on:
            - wordpress
        volumes:
            - wordpress:/var/www/html
        environment:
            DOMAIN_NAME: ${DOMAIN_NAME}
            EMAIL: ${WP_ADMIN_MAIL}

networks:
    network:


volumes:
    wordpress:
    mariadb:
